var Images = {
    "Seth": {file:"images/Seth.jpeg", label: "Seth"},
    "Shaggy (Adam)":{file:"images/Shaggy.jpeg", label:"Shaggy"},
    "Rosey (Jacob)":{file:"images/Rosey.jpeg", label:"Rosey"},
    "Ephemer (James)":{file:"images/Ephemer.jpeg", label:"Ephemer"},
    "Orlen (B man)":{file:"images/Orlan.jpeg", label:"Orlen"},
    "Gago (Blake)":{file:"images/Gago.jpeg", label:"Gago"},
    "Goop (Alan)":{file:"images/Goop.png", label:"Goop"},
    "pastor":{file: "images/pastor.jpeg"},
    "cook":{file: "images/cook.jpeg"},
    "spider":{file: "images/spider.jpeg"},
    "big spider":{file: "images/bigspider.jpeg"},
    "skeleton":{file: "images/skeleton.jpeg"},
    "mummy":{file: "images/mummy.jpeg"},
    "shadow":{file: "images/shadow.svg"},
    "warrior":{file: "images/warrior.jpeg"},
    "archer":{file: "images/archer.jpeg"},
    "ghost":{file: "images/ghost.jpeg"},
    "normal circle":{file: "images/circle.jpeg"},
    "normal circle (large)":{file: "images/circle.jpeg", size:"large"},
    "red circle":{file: "images/redcircle.jpeg"},
    "red circle (large)":{file: "images/redcircle.jpeg", size:"large"},
    "blue circle":{file: "images/bluecircle.jpeg"},
    "blue circle (large)":{file: "images/bluecircle.jpeg", size:"large"},
    "square":{file: "images/square.jpeg"},
    "square (large)":{file: "images/square.jpeg", size:"large"},
    "nerd": {file: "images/nerd.jpeg"},
    "lich": {file: "images/lich.png", size:"large"},
    "undead caster": {file: "images/lich.png"},
    "mage": {file: "images/mage.png"},
    "wizard": {file: "images/wizard.png"},
    "thief": {file: "images/thief.png"},
    "rogue": {file: "images/rogue.jpeg"},
    "spy": {file: "images/spy.png"},
    "priest": {file: "images/priest.png"},
    "orc": {file: "images/orc.png", size: "large"},
    "half orc": {file: "images/orc.png"},
    "elf female": {file: "images/elf female.png"},
    "elf male": {file: "images/elf male.png"},
    "goblin": {file: "images/goblin.png"},
    "human male": {file: "images/human male.png"},
    "human female": {file: "images/human female.png"},
    "gnome": {file: "images/gnome.png"},
    "dwarf": {file: "images/dwarf.png"}
}